apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    type: local
  name: claim-log-1
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
  storageClassName: manual
  volumeName: local-pv
